/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LicensingRouteImport } from './routes/licensing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as Auth2faRouteImport } from './routes/auth.2fa'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppApplicationsIndexRouteImport } from './routes/app.applications.index'
import { Route as AppPaymentsResultRouteImport } from './routes/app.payments.result'
import { Route as AppPaymentsRequestRouteImport } from './routes/app.payments.request'
import { Route as AppPaymentsReceiptRouteImport } from './routes/app.payments.receipt'
import { Route as AppPaymentsEftRouteImport } from './routes/app.payments.eft'
import { Route as AppPaymentsCheckoutRouteImport } from './routes/app.payments.checkout'
import { Route as AppApplicationsTrackingRouteImport } from './routes/app.applications.tracking'
import { Route as AppApplicationsSuccessRouteImport } from './routes/app.applications.success'
import { Route as AppApplicationsReviewRouteImport } from './routes/app.applications.review'
import { Route as AppApplicationsNewRouteImport } from './routes/app.applications.new'

const LicensingRoute = LicensingRouteImport.update({
  id: '/licensing',
  path: '/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const Auth2faRoute = Auth2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsResultRoute = AppPaymentsResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsRequestRoute = AppPaymentsRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsReceiptRoute = AppPaymentsReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsEftRoute = AppPaymentsEftRouteImport.update({
  id: '/eft',
  path: '/eft',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsCheckoutRoute = AppPaymentsCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppApplicationsTrackingRoute = AppApplicationsTrackingRouteImport.update({
  id: '/applications/tracking',
  path: '/applications/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsSuccessRoute = AppApplicationsSuccessRouteImport.update({
  id: '/applications/success',
  path: '/applications/success',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsReviewRoute = AppApplicationsReviewRouteImport.update({
  id: '/applications/review',
  path: '/applications/review',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsNewRoute = AppApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/licensing': typeof LicensingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/app/applications/review': typeof AppApplicationsReviewRoute
  '/app/applications/success': typeof AppApplicationsSuccessRoute
  '/app/applications/tracking': typeof AppApplicationsTrackingRoute
  '/app/payments/checkout': typeof AppPaymentsCheckoutRoute
  '/app/payments/eft': typeof AppPaymentsEftRoute
  '/app/payments/receipt': typeof AppPaymentsReceiptRoute
  '/app/payments/request': typeof AppPaymentsRequestRoute
  '/app/payments/result': typeof AppPaymentsResultRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/licensing': typeof LicensingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/app/applications/review': typeof AppApplicationsReviewRoute
  '/app/applications/success': typeof AppApplicationsSuccessRoute
  '/app/applications/tracking': typeof AppApplicationsTrackingRoute
  '/app/payments/checkout': typeof AppPaymentsCheckoutRoute
  '/app/payments/eft': typeof AppPaymentsEftRoute
  '/app/payments/receipt': typeof AppPaymentsReceiptRoute
  '/app/payments/request': typeof AppPaymentsRequestRoute
  '/app/payments/result': typeof AppPaymentsResultRoute
  '/app/applications': typeof AppApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/licensing': typeof LicensingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/2fa': typeof Auth2faRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/applications/new': typeof AppApplicationsNewRoute
  '/app/applications/review': typeof AppApplicationsReviewRoute
  '/app/applications/success': typeof AppApplicationsSuccessRoute
  '/app/applications/tracking': typeof AppApplicationsTrackingRoute
  '/app/payments/checkout': typeof AppPaymentsCheckoutRoute
  '/app/payments/eft': typeof AppPaymentsEftRoute
  '/app/payments/receipt': typeof AppPaymentsReceiptRoute
  '/app/payments/request': typeof AppPaymentsRequestRoute
  '/app/payments/result': typeof AppPaymentsResultRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/licensing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/app/applications/new'
    | '/app/applications/review'
    | '/app/applications/success'
    | '/app/applications/tracking'
    | '/app/payments/checkout'
    | '/app/payments/eft'
    | '/app/payments/receipt'
    | '/app/payments/request'
    | '/app/payments/result'
    | '/app/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/licensing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/app/applications/new'
    | '/app/applications/review'
    | '/app/applications/success'
    | '/app/applications/tracking'
    | '/app/payments/checkout'
    | '/app/payments/eft'
    | '/app/payments/receipt'
    | '/app/payments/request'
    | '/app/payments/result'
    | '/app/applications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/licensing'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/messages'
    | '/app/notifications'
    | '/app/payments'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/auth/2fa'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify'
    | '/app/applications/new'
    | '/app/applications/review'
    | '/app/applications/success'
    | '/app/applications/tracking'
    | '/app/payments/checkout'
    | '/app/payments/eft'
    | '/app/payments/receipt'
    | '/app/payments/request'
    | '/app/payments/result'
    | '/app/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  FaqRoute: typeof FaqRoute
  LicensingRoute: typeof LicensingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/licensing': {
      id: '/licensing'
      path: '/licensing'
      fullPath: '/licensing'
      preLoaderRoute: typeof LicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/2fa': {
      id: '/auth/2fa'
      path: '/2fa'
      fullPath: '/auth/2fa'
      preLoaderRoute: typeof Auth2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/result': {
      id: '/app/payments/result'
      path: '/result'
      fullPath: '/app/payments/result'
      preLoaderRoute: typeof AppPaymentsResultRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/request': {
      id: '/app/payments/request'
      path: '/request'
      fullPath: '/app/payments/request'
      preLoaderRoute: typeof AppPaymentsRequestRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/receipt': {
      id: '/app/payments/receipt'
      path: '/receipt'
      fullPath: '/app/payments/receipt'
      preLoaderRoute: typeof AppPaymentsReceiptRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/eft': {
      id: '/app/payments/eft'
      path: '/eft'
      fullPath: '/app/payments/eft'
      preLoaderRoute: typeof AppPaymentsEftRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/checkout': {
      id: '/app/payments/checkout'
      path: '/checkout'
      fullPath: '/app/payments/checkout'
      preLoaderRoute: typeof AppPaymentsCheckoutRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/applications/tracking': {
      id: '/app/applications/tracking'
      path: '/applications/tracking'
      fullPath: '/app/applications/tracking'
      preLoaderRoute: typeof AppApplicationsTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/success': {
      id: '/app/applications/success'
      path: '/applications/success'
      fullPath: '/app/applications/success'
      preLoaderRoute: typeof AppApplicationsSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/review': {
      id: '/app/applications/review'
      path: '/applications/review'
      fullPath: '/app/applications/review'
      preLoaderRoute: typeof AppApplicationsReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applications/new': {
      id: '/app/applications/new'
      path: '/applications/new'
      fullPath: '/app/applications/new'
      preLoaderRoute: typeof AppApplicationsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPaymentsRouteChildren {
  AppPaymentsCheckoutRoute: typeof AppPaymentsCheckoutRoute
  AppPaymentsEftRoute: typeof AppPaymentsEftRoute
  AppPaymentsReceiptRoute: typeof AppPaymentsReceiptRoute
  AppPaymentsRequestRoute: typeof AppPaymentsRequestRoute
  AppPaymentsResultRoute: typeof AppPaymentsResultRoute
}

const AppPaymentsRouteChildren: AppPaymentsRouteChildren = {
  AppPaymentsCheckoutRoute: AppPaymentsCheckoutRoute,
  AppPaymentsEftRoute: AppPaymentsEftRoute,
  AppPaymentsReceiptRoute: AppPaymentsReceiptRoute,
  AppPaymentsRequestRoute: AppPaymentsRequestRoute,
  AppPaymentsResultRoute: AppPaymentsResultRoute,
}

const AppPaymentsRouteWithChildren = AppPaymentsRoute._addFileChildren(
  AppPaymentsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPaymentsRoute: typeof AppPaymentsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppApplicationsNewRoute: typeof AppApplicationsNewRoute
  AppApplicationsReviewRoute: typeof AppApplicationsReviewRoute
  AppApplicationsSuccessRoute: typeof AppApplicationsSuccessRoute
  AppApplicationsTrackingRoute: typeof AppApplicationsTrackingRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPaymentsRoute: AppPaymentsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppApplicationsNewRoute: AppApplicationsNewRoute,
  AppApplicationsReviewRoute: AppApplicationsReviewRoute,
  AppApplicationsSuccessRoute: AppApplicationsSuccessRoute,
  AppApplicationsTrackingRoute: AppApplicationsTrackingRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  Auth2faRoute: typeof Auth2faRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  Auth2faRoute: Auth2faRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  FaqRoute: FaqRoute,
  LicensingRoute: LicensingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
